# Generated by Django 6.0.7 on 2026-08-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('transcript', models.TextField()),
                ('technical_score', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
