# Generated by Django 6.0.7 on 2026-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='session_id',
            field=models.CharField(default='default-session', max_length=100),
            preserve_default=False,
        ),
    ]
